### ISSUE TITLE
Prijedlog: dodati riječ "zamrzávati".

### ISSUE THREAD

**Issue by alex-kovac** [krunose/hunspell-hr#5]
Uz ispriku, dok ne naučim kako dodavati riječi, predlažem dodati riječ: _zamrzavati_ (s naglaskom: _zamrzávati_.) i izvedene oblike: _zamrzavanje_, _zamrzavajući_. Riječ je nesvršeni oblik glagola _zamrznuti_.

**Comment by krunose** [comment]
Riječ će biti dodana ovaj vikend. Isprike na dugom čekanju na odgovor. Po dodavanju riječi, zatvorit ću _issue_. Također, mogu pomoći i s učenjem kako dodati riječ.

**Comment by krunose** [comment]
Pozdrav, riječ „zamrzavati” dodana je u rječnik. Rječnik će prepoznati prezent, gl. imenicu, imperfekt, glagolski pridjev radni i trpni, ali u vezi s potonjim postoji problem jer rječnik prihvaća i „zamrzavanoga”, ali jednojezični rječnici hrvatskoga jezika bilježe samo gl. prid. trpni na -an (zamrzavan, zamrzavana, zamrzavano, zamrzavani, zamrzavane, zamrzavana), ne i pridjev „zamrzavan” (zamrzavanoga, zamrzavanih...). U rječnicima postoji „zamrznut”, ali to je drugi pridjev. Međutim, na internetu sam pronašao potvrdu pridjeva „zamrzavan” (zamrzavanoga mesa), pa mislim da smo se izvukli i rječnik, zapravo, neće dozvoljavati nepostojeće oblike. Postoje određena ograničenja koja bi trebalo riješiti u trećoj inačici rječnika (jednoga dana). Posla ima mnogo, a vremena je malo.

**Comment by alex-kovac** [comment]
Zaista nema potrebe za isprikom! Hvala puno za trud oko ovoga projekta. Počeo sam se informirati o načinu dodavanja riječi i pravila. Ponešto mi je shvatljivo, ali oko većine tek moram _omotati mozak_. Računalstvo nije moje primarno područje (dizajnerska znanost) pa mi je to hendikep :)... Ako nekim čudom postoji savjet gdje naučiti ili čarobno brz put do shvaćanja, rado bih čuo o tome :)
