### ISSUE TITLE
Failes to install from AUR

### ISSUE THREAD

**Issue by andrej1919** [krunose/hunspell-hr#7]
Fails to install from AUR due to bstdar failure related to the current locale.
My suspicion is that when extracted on a system with en_US locale, the diacriticals in file names cause this issue:

```
bsdtar: Failed to set default locale
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Error exit delayed from previous errors.
```

**Comment by krunose** [comment]
Hi! We can't fix any issues regarding installing dictionaries as we only provide rules, not (installable) packages. Arch package maintainer(s) may pull files from here (and they do, see link at the end), but we don't know anything about the process or related issues. Maybe this wiki page can steer you in the right direction: [AUR (en) - hunspell-hr](https://aur.archlinux.org/packages/hunspell-hr).

What we can do is improve dictionary by adding and correcting words, so feel free to send feedback.
